services:
  hadoop-master:
    build: .
    container_name: hadoop-master
    hostname: hadoop-master
    ports:
      - "9870:9870" # HDFS NameNode Web UI
      - "8020:8020" # HDFS NameNode HDFS API
      - "9864:9864" # HDFS DataNode Web UI
      - "8088:8088" # YARN ResourceManager Web UI
      - "8042:8042" # YARN NodeManager Web UI
      - "9000:9000" # fs.DefaultFS
    volumes:
      - hadoop-master-data:/usr/local/hadoop
    networks:
      - hadoop

  hadoop-slave1:
    build: .
    container_name: hadoop-slave1
    hostname: hadoop-slave1
    depends_on:
      - hadoop-master
    volumes:
      - hadoop-slave1-data:/usr/local/hadoop
    networks:
      - hadoop

  hadoop-slave2:
    build: .
    container_name: hadoop-slave2
    hostname: hadoop-slave2
    depends_on:
      - hadoop-master
    volumes:
      - hadoop-slave2-data:/usr/local/hadoop
    networks:
      - hadoop

  hadoop-slave3:
    build: .
    container_name: hadoop-slave3
    hostname: hadoop-slave3
    depends_on:
      - hadoop-master
    volumes:
      - hadoop-slave3-data:/usr/local/hadoop
    networks:
      - hadoop

networks:
  hadoop:
    driver: bridge

volumes:
  hadoop-master-data:
  hadoop-slave1-data:
  hadoop-slave2-data:
  hadoop-slave3-data:
