version: "2"
services:
  master:
    build: .
    hostname: namenode
    command: ./start.sh namenode
    ports:
      - 8088:8088
      - 9870:9870
      - 19888:19888
    volumes:
      - type: bind
        source: mapreduce/
        target: /hadoop/mapreduce/
  worker1:
    depends_on:
      - master
    build: .
    hostname: worker1
    command: ./start.sh worker1
    ports:
      - 9864:9864
  worker2:
    depends_on:
      - master
    build: .
    hostname: worker2
    command: ./start.sh worker
