version: '3.8'

services:
  spark-master:
    image: spark:latest
    container_name: spark-master
    hostname: spark-master
    platform: linux/amd64
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - SPARK_MODE=master
    volumes:
      - /users/admin/softeer/week4/m1/data:/data
    networks:
      - spark-network

  spark-worker-1:
    image: spark:latest
    container_name: spark-worker-1
    hostname: spark-worker-1
    platform: linux/amd64
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    volumes:
      - /users/admin/softeer/week4/m1/data:/data
    networks:
      - spark-network

  spark-worker-2:
    image: spark:latest
    container_name: spark-worker-2
    hostname: spark-worker-2
    platform: linux/amd64
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    volumes:
      - /users/admin/softeer/week4/m1/data:/data
    networks:
      - spark-network

  spark-history:
    image: spark:latest
    container_name: spark-history
    hostname: spark-history
    ports:
      - "18080:18080" # Spark History Server
    volumes:
      - /users/admin/softeer/week4/m1/data:/data
    networks:
      - spark-network
    environment:
      - SPARK_MODE=history
      - SPARK_HISTORY_OPTS=-Dspark.history.fs.logDirectory=/data/spark-events
    depends_on:
      - spark-master

networks:
  spark-network:
    driver: bridge

