version: "2"
services:
  master:
    build: .
    hostname: master
    ports:
      - 4040:4040
      - 4041:4041
      - 7077:7077
      - 8080:8080
    volumes:
      - type: bind
        source: userdata/
        target: /spark/userdata/
    command: ./start.sh master
  worker1:
    depends_on:
      - master
    build: .
    hostname: worker1
    ports:
      - 8081:8081
    volumes:
      - type: bind
        source: userdata/
        target: /spark/userdata/
    command: ./start.sh worker
  worker2:
    depends_on:
      - master
    build: .
    hostname: worker2
    volumes:
      - type: bind
        source: userdata/
        target: /spark/userdata/
    command: ./start.sh worker