#!/bin/bash

# Update and install Docker
yum update -y
yum install -y docker

# Start and enable Docker service
systemctl start docker
systemctl enable docker

# Install AWS CLI v2
curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
unzip awscliv2.zip
sudo ./aws/install

# Set environment variable for AWS region
AWS_REGION="ap-northeast-2"

# Retrieve AWS account ID dynamically
AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)

# Login to AWS ECR
aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

# Add ec2-user to the docker group
usermod -a -G docker ec2-user

# Pull and run the Docker container
docker pull $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/softeer-jupyterlab:1.0.0
docker run -d --name softeer-jupyterlab -p 8888:8888 $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/softeer-jupyterlab:1.0.0
