version: '3.8'

services:
  spark-master:
    image: spark-image
    build: .
    container_name: spark-master
    environment:
      - ROLE=master
    ports:
      - "8080:8080" 
      - "7077:7077" 
      - "4040:4040" 
    networks:
      - spark-network

  spark-worker1:
    image: spark-image
    build: .
    container_name: spark-worker1
    environment:
      - ROLE=worker
    depends_on:
      - spark-master
    networks:
      - spark-network

  spark-worker2:
    image: spark-image
    build: .
    container_name: spark-worker2
    environment:
      - ROLE=worker
    ports:
      - "8081:8081"
    depends_on:
      - spark-master
    networks:
      - spark-network

networks:
  spark-network:
    driver: bridge

