version: '3'

services:
  spark-master:
    image: spark-jupyter-chrome:latest
    container_name: spark-master
    build: .
    ports:
      - "8080:8080"
      - "7077:7077"
      - "8889:8888"
    volumes:
      - ./data:/mnt/data  # Host의 ./data 디렉토리를 컨테이너의 /mnt/data 디렉토리에 마운트
    environment:
      - SPARK_MODE=master
    command: ["/bin/bash", "-c", "/opt/bitnami/spark/bin/spark-class org.apache.spark.deploy.master.Master & jupyter notebook --ip=0.0.0.0 --allow-root --no-browser --NotebookApp.token='' --NotebookApp.password=''"]

  spark-worker-1:
    image: bitnami/spark:3.2.0
    container_name: spark-worker-1
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=1g
    command: ["/bin/bash", "-c", "/opt/bitnami/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077"]
