version: "3.8"
services:
  hadoop-master:
    image: jnamu/spark-analysis-node:latest
    container_name: hadoop-master
    hostname: hadoop-master
    ports:
      - "8888:8888" # Jupyter Notebook
      - "8080:8080" # Spark Master UI
      - "4040:4040" # Spark Job UI
      - "7077:7077"
      - "7777:7777"
      - "9870:9870" # HDFS NameNode Web UI
      - "8020:8020" # HDFS NameNode HDFS API
      - "8088:8088" # YARN ResourceManager Web
      - "9000:9000" # fs.DefaultFS
    volumes:
      - spark-rdd_hadoop-master-data:/opt/hadoop/data

  hadoop-worker-1:
    image: jnamu/spark-analysis-node:latest
    container_name: hadoop-worker-1
    hostname: hadoop-worker-1
    depends_on:
      - hadoop-master
    ports:
      - "8081:8081" # Spark Worker UI
      - "9864:9864" # HDFS DataNode Web UI
      - "8042:8042" # YARN NodeManager Web UI
    volumes:
      - spark-rdd_hadoop-slave1-data:/opt/hadoop/data

  hadoop-worker-2:
    image: jnamu/spark-analysis-node:latest
    container_name: hadoop-worker-2
    hostname: hadoop-worker-2
    depends_on:
      - hadoop-master
    ports:
      - "8082:8081" # Spark Worker UI
      - "9865:9864" # HDFS DataNode Web UI
      - "8043:8042" # YARN NodeManager Web UI
    volumes:
      - spark-rdd_hadoop-slave2-data:/opt/hadoop/data

volumes:
  spark-rdd_hadoop-master-data:
    external: true
  spark-rdd_hadoop-slave1-data:
    external: true
  spark-rdd_hadoop-slave2-data:
    external: true