version: "3.8"

services:
  hadoop-single-node:
    image: hadoop-single-node
    container_name: hadoop-single-node
    ports:
      - "9870:9870"
      - "8088:8088"
      - "9000:9000"
      - "9864:9864"
    volumes:
      - hadoop-volume:/hadoop/dfs
    command: ["/usr/local/bin/start-hadoop.sh"]
    environment:
      - JAVA_HOME=/usr/lib/jvm/java-8-openjdk-arm64
      - HADOOP_HOME=/opt/hadoop
      - PATH=$PATH:/opt/hadoop/bin:/opt/hadoop/sbin
      - HDFS_NAMENODE_USER=hdfs
      - HDFS_DATANODE_USER=hdfs
      - HDFS_SECONDARYNAMENODE_USER=hdfs
      - YARN_RESOURCEMANAGER_USER=yarn
      - YARN_NODEMANAGER_USER=yarn

volumes:
  hadoop-volume:
    driver: local
